services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "mongodb://root:example@localhost:27017/admin",
          "--eval",
          "db.runCommand({ ping: 1 })",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks: [app-net]

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        NODE_VERSION: "22"
        NODE_ENV: ${NODE_ENV}
    image: project-backend:dev
    working_dir: /repo/backend
    command: pnpm dev
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
      JWT_SECRET: ${JWT_SECRET:-change-me-in-shell}
      MONGO_URI: ${MONGO_URI:-mongodb://root:example@mongodb:27017/app?authSource=admin}
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
      FRONTEND_HOST: ${FRONTEND_HOST:-lit-contact-frontend.liam-gattegno.fr}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/repo/backend:cached
      - node_modules_backend:/repo/backend/node_modules
      - node_modules_shared:/repo/packages/shared/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks: [app-net, proxy]
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # Backend listens on 3000 inside the container
      - traefik.http.services.backend.loadbalancer.server.port=3000

      # HTTPS router for backend API
      - traefik.http.routers.backend.rule=Host(`${BACKEND_HOST:-lit-contact-api.liam-gattegno.fr}`)
      - traefik.http.routers.backend.entrypoints=https-external
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=cloudflare
      - traefik.http.routers.backend.service=backend

      # HTTP -> HTTPS redirect router
      - traefik.http.routers.backend-redirect.rule=Host(`${BACKEND_HOST:-lit-contact-api.liam-gattegno.fr}`)
      - traefik.http.routers.backend-redirect.entrypoints=http-external
      - traefik.http.routers.backend-redirect.middlewares=redirect-to-https

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NODE_VERSION: "22"
        NODE_ENV: ${NODE_ENV}
    image: project-frontend:dev
    working_dir: /repo/frontend
    command: pnpm dev --host 0.0.0.0
    environment:
      NODE_ENV: development
      VITE_API_URL: https://${BACKEND_HOST:-lit-contact-api.liam-gattegno.fr}
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/repo/frontend:cached
      - ./packages/shared:/repo/packages/shared:cached
      - node_modules_frontend:/repo/frontend/node_modules
      - node_modules_shared:/repo/packages/shared/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks: [app-net, proxy]
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # Vite dev server listens on 5173 inside the container
      - traefik.http.services.frontend.loadbalancer.server.port=5173

      # HTTPS router
      - traefik.http.routers.frontend.rule=Host(`${FRONTEND_HOST:-lit-contact-frontend.liam-gattegno.fr}`)
      - traefik.http.routers.frontend.entrypoints=https-external
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=cloudflare
      - traefik.http.routers.frontend.service=frontend

      # HTTP -> HTTPS redirect router
      - traefik.http.routers.frontend-redirect.rule=Host(`${FRONTEND_HOST:-lit-contact-frontend.liam-gattegno.fr}`)
      - traefik.http.routers.frontend-redirect.entrypoints=http-external
      - traefik.http.routers.frontend-redirect.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true

volumes:
  mongo_data:
  node_modules_backend:
  node_modules_shared:
  node_modules_frontend:

networks:
  app-net:
    driver: bridge
  proxy:
    external: true
    name: proxy
